### ISSUE TITLE
Error Fighting

### ISSUE THREAD

**Issue by c00t-doggo** [telperion/saturday-morning#11]
I'm fighting with this error. Is this my fault or a fault of the program?
![image](https://user-images.githubusercontent.com/72281312/124123010-0bde1800-da77-11eb-8080-43feda54e9c1.png)

**Comment by kimicake** [comment]
I'm getting this error too, i made my chart in Arrow Vortex, Challenge Doubles chart.

**Comment by c00t-doggo** [comment]
Found the issue, it is the way I made the simfile in vortex.

**Comment by Cacx101** [comment]
> Found the issue, it is the way I made the simfile in vortex.

Could you clarify exactly what "way" you made the simfile? Running into this exact same issue in Vortex myself and can't for the life of me figure out what I'm doing wrong.

**Comment by c00t-doggo** [comment]
For some reason, official charts worked like wonders, so it probably has to do with shit like description or title missing, try and fill out anything you can.
