### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by tahiadz1962** [telperion/saturday-morning#2]
It just shows a lot of errors. That's all for now.

**Comment by telperion** [comment]
Can you post screenshots of the errors you're seeing?

**Comment by tahiadz1962** [comment]
Wait...

**Comment by tahiadz1962** [comment]
![error](https://user-images.githubusercontent.com/79606983/113067278-06c4b080-918a-11eb-97ce-745cf9e1bb5f.PNG)
Also, it doesn't let me drag the .SM or .SCC files.

**Comment by telperion** [comment]
Gotcha. The program says it's being opened without drag-or-drop, but I think the best solution is for me to handle that situation more gracefully :) I'm planning on adding a button to navigate within the app to a song of your choice.

**Comment by tahiadz1962** [comment]
Okay. Thanks!
